spring:
  config:
    activate:
      on-profile: local
  # DB 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

logging:
  level:
    root: INFO
    com.paystream.user: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
