server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  # DB 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres} # local -> docker postgresql
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 50           # 한 번에 모아서 보낼 쿼리 개수
        order_inserts: true           # insert 문 정렬하여 배치 효율 최적화
        order_updates: true           # update 문 정렬
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

file:
  upload-dir: ${user.home}/paystream/uploads/