server:
  port: 0

spring:
  application:
    name: inventory-service
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

eureka:
  client:
    enabled: false

file:
  upload-dir:
    os:
      window: ${java.io.tmpdir}/paystream-test/
      mac: ${java.io.tmpdir}/paystream-test/
      linux: ${java.io.tmpdir}/paystream-test/