server:
  port: 0

spring:
  application:
    name: inventory-service
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000
        jdbc.batch_size: 50           # 한 번에 모아서 보낼 쿼리 개수
        order_inserts: true           # insert 문 정렬하여 배치 효율 최적화
        order_updates: true           # update 문 정렬
        generate_statistics: true     # 실행 통계를 로그에 출력
  kafka:
    listener:
      auto-startup: false

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

eureka:
  client:
    enabled: false

file:
  upload-dir: ${java.io.tmpdir}/paystream-test/