server:
  port: 8081

spring:
  application:
    name: inventory-service
  profiles:
    default: local
  # kafka
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:29092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest # consumer 그룹이 미리 안만들어져있다면 미리 생성해서 가장 빠른 메시지를 읽어옴, 미리 만들어져있다면 존재하는 consumer 부터 읽음, 만약 이 설정을 안하게 된다면 기존에 쌓여있던 메시지는 읽지 않고 무시하게됌.
      group-id: inventory-group

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# swgger 설정
springdoc:
  api-docs:
    enabled: true # OpenAPI 인터페이스의 사용 여부 결정
  swagger-ui:
    enabled: true # Swagger-ui의 사용 여부 결정
    tagsSorter: alpha # Swagger-ui에서 Tag의 정렬 기준을 설정 (알파벳순)
    operations-sorter: alpha # Swagger-ui에서 개별 API에 해당하는 Operation의 정렬 기준을 설정 (알파벳순)
    display-request-duration: true # Swagger-ui에서 API 실행 시 처리 소요 시간의 표시 여부를 설정

logging:
  level:
    com.paystream.inventory: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG # jpa logging