spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    com.paystream.payment: INFO
    org.springframework.cloud: INFO

