spring:
  config:
    activate:
      on-profile: local

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    com.paystream.payment: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
