plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.paystream'
version = '0.0.1-SNAPSHOT'
description = 'NotificationService'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springCloudVersion', "2025.0.0")
}

dependencies {
    // Spring Web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    
    // Validation - DTO 검증을 위한 의존성
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    
    // JPA - 엔티티/리포지토리 사용을 위한 의존성
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    
    // 개발용 내장 DB(H2) - 로컬 개발과 테스트에 사용
    runtimeOnly 'com.h2database:h2'
    
    // Eureka Client - 서비스 디스커버리 등록
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    
    // Actuator - 헬스 체크 및 모니터링
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    
    // Swagger - API 문서화
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9'
    
    // 공통 라이브러리 가져옴
    implementation project(':common:core')
    
    // Kafka - 이벤트 기반 알림 수신 (추후 활성화)
    // implementation 'org.springframework.kafka:spring-kafka'
    
    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    
    // DevTools - 개발 편의성
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    
    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

