server:
  port: 8761

spring:
  application:
    name: EurekaServer

eureka:
  client:
    fetch-registry: false # Eureka ??? ??? ??? ??? ????? ?? ?? ??, ??? ???? ??? ???? ??
    register-with-eureka: false # Eureka ??? ??? ???? ?? ??? ???? ??, ??? ???? ??? ???? ??.
  server:
    enable-self-preservation: false # ??? ???? ??? ?? ??? ??? ??? ?? ???? ?? ??, ?????? true? ??
    response-cache-update-interval-ms: 5000 # Eureka ??? ?? ???? ?? (5?)
    eviction-interval-timer-in-ms: 10000 # ???????? ????? ?????? ???? ?? (10?)
