server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        exclude: health,info
    jmx:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    urls[0]:
      name: 상품 및 재고 서비스
      url: http://localhost:8000/api/inventory/v3/api-docs
    urls[1]:
      name: 알림 서비스
      url: http://localhost:8000/api/notification/v3/api-docs
    urls[2]:
      name: 유저 서비스
      url: http://localhost:8000/api/users/v3/api-docs


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-swagger
              uri: lb://user-service
              predicates:
                - Path=/api/users/v3/api-docs/**
              filters:
                - RewritePath=/api/users/(?<segment>.*), /${segment}
                - AddRequestHeader=X-Service-Name, user-service

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - RewritePath=/api/users/(?<segment>.*), /users/${segment}
                - AddRequestHeader=X-Service-Name, user-service

            - id: inventory-service-swagger
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory/v3/api-docs/**
                - Method=GET
              filters:
                - RewritePath=/api/inventory/(?<path>.*), /$\{path}

            - id: inventory-service-stores-root
              uri: lb://inventory-service
              predicates:
                - Path=/api/stores
              filters:
                - RewritePath=/api/stores, /stores
                - AddRequestHeader=X-Service-Name, inventory-service

            - id: inventory-service-stores-segment
              uri: lb://inventory-service
              predicates:
                - Path=/api/stores/**
              filters:
                - RewritePath=/api/stores/(?<segment>.*), /stores/$\{segment}
                - AddRequestHeader=X-Service-Name, inventory-service


# 인증 로직을 거치지 않는 Endpoint
whitelist:
  paths:
    - /swagger-ui/**
    - /v3/api-docs/**
    - /swagger-ui.html
    - /stores