server:
  port: 0

spring:
  application:
    name: api-gateway
  config:
    activate:
      on-profile: test

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        exclude: health,info
    jmx:
      exposure:
        include: "*"