server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        exclude: health,info
    jmx:
      exposure:
        include: "*"

spring:
  application:
    name: api-gateway

springdoc:
  swagger-ui:
    urls[0]:
      name: 상품 및 재고 서비스
      url: http://localhost:8000/api/inventories/v3/api-docs
    urls[1]:
      name: 알림 서비스
      url: http://localhost:8000/api/notification/v3/api-docs
    urls[2]:
      name: 주문 서비스
      url: http://localhost:8000/api/orders/v3/api-docs
    urls[3]:
      name: 결제 서비스
      url: http://localhost:8000/api/payments/v3/api-docs
    urls[4]:
      name: 유저 서비스
      url: http://localhost:8000/api/users/v3/api-docs

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

logging:
  level:
    io.github.resilience4j: DEBUG
    org.springframework.cloud.gateway: DEBUG