server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        exclude: health,info
    jmx:
      exposure:
        include: "*"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - RewritePath=/api/users/(?<segment>.*), /users/${segment}
                - AddRequestHeader=X-Service-Name, user-service

            - id: inventory-service-stores-root
              uri: lb://inventory-service
              predicates:
                - Path=/api/stores
              filters:
                - RewritePath=/api/stores, /stores
                - AddRequestHeader=X-Service-Name, inventory-service

            - id: inventory-service-stores-segment
              uri: lb://inventory-service
              predicates:
                - Path=/api/stores/**
              filters:
                - RewritePath=/api/stores/(?<segment>.*), /stores/$\{segment}
                - AddRequestHeader=X-Service-Name, inventory-service
